# Generated by Django 4.1.6 on 2023-02-13 02:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_grade_note_title_alter_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(default='pic', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
