# Generated by Django 4.1.6 on 2023-02-13 04:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='body',
            new_name='content_1',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RemoveField(
            model_name='note',
            name='grade',
        ),
        migrations.AddField(
            model_name='note',
            name='content_2',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='note',
            name='content_3',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='note',
            name='grade_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='grade_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='grade_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='image_2',
            field=models.ImageField(default='pic', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='note',
            name='image_3',
            field=models.ImageField(default='pic', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
